version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - . :/usr/src/photo_filter/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=photo_filter_user
      - POSTGRES_PASSWORD=photo_filter_password
      - POSTGRES_DB=photo_filter_dev
volumes:
  postgres_data: